FROM msopenstack/sentinel-centos:latest
 
RUN yum update -y
RUN puppet module install puppetlabs-stdlib
RUN git clone https://github.com/openstack-hyper-v/puppet-openwsman /etc/puppet/modules/openwsman
RUN puppet apply --debug --trace --verbose --modulepath=/etc/puppet/modules /etc/puppet/modules/openwsman/tests/init.pp
